### ISSUE TITLE
How to send two http request one by one in an action event?

### ISSUE THREAD

**Issue by xho22** [zslucky/redux-fetch-middleware#10]
like：
`promise.then().then()`
not: 
`promise.all`

**Comment by zslucky** [comment]
@xho22 , this middleware only support simple and single request for now as the design, for chained request, I think you can choose the other middleware, like promise-middleware, redux-saga, async middleware etc... 

Or you can give some suggestions for me or yourself to add the feature in this project 😄

**Comment by CosticaPuntaru** [comment]
pretty sure you can do `this.props.firstAction().then(()=> this.props.secondAction())` as middleware returns the fetch promise

**Comment by zslucky** [comment]
closed by right case
